"""Initial migration

Revision ID: f38180b24285
Revises: 3d21b9746d2e
Create Date: 2025-05-01 20:39:27.360865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38180b24285'
down_revision = '3d21b9746d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference_allergy', schema=None) as batch_op:
        batch_op.alter_column('preference_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('allergy_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint('preference_allergy_preference_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('preference_allergy_allergy_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'preferences', ['preference_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'allergies', ['allergy_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preference_allergy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('preference_allergy_allergy_id_fkey', 'allergies', ['allergy_id'], ['id'])
        batch_op.create_foreign_key('preference_allergy_preference_id_fkey', 'preferences', ['preference_id'], ['id'])
        batch_op.alter_column('allergy_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('preference_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
